# Generated by Django 4.2.3 on 2023-07-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('digital_property', models.CharField(max_length=50)),
                ('signature', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
                ('PropertyImage', models.ImageField(upload_to='images')),
            ],
        ),
    ]
